### ISSUE TITLE
NoSuchMethod

### ISSUE THREAD

**Issue by zap8600** [termux/termux-x11#149]
Trying to run termux-x11
All I get is this
`~ $ termux-x11
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
$XDG_RUNTIME_DIR is unset.
Exporting default value (/data/data/com.termux/files/usr/tmp).
java.lang.NoSuchMethodError: No interface method startActivity(Landroid/app/IApplicationThread;Ljava/lang/String;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/os/IBinder;Ljava/lang/String;IILandroid/app/ProfilerInfo;Landroid/os/Bundle;)I in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
        at com.termux.x11.starter.Compat.startActivity(Compat.java:27)
        at com.termux.x11.starter.Starter.startActivity(Starter.java:144)
        at com.termux.x11.starter.Starter.onRun(Starter.java:80)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:42)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)
Android reported activity started but we did not get any respond
Looks like we failed to start activity.
~ $`

**Comment by EralpCelebi** [comment]
Same problem here :/

**Comment by EralpCelebi** [comment]
I think this is mentioned in another issue though, you might want to check out #146

**Comment by twaik** [comment]
I am aware of the problem. I am on it.
Duplicate #146

**Comment by zap8600** [comment]
This worked. Thanks
