### ISSUE TITLE
Unable to connect `termux-11`

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#286]
recent i rooted my devices and hard reset devices.
install `termux-app` and `termux-11` latest build from scretch.
and try to connect `termux-11` but getting this log.

> termux info
```bash
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~aMrwRrQ-0o7FRN0PxkfH9w==/com.termux-fIfKNTyUu08U2nXujWwZyg==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=16314
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c255,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c255,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10255
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+b1b36a3
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+b1b36a3
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
12
Kernel build information:
Linux localhost 4.14.190-perf-gc02e19ad9060 #1 SMP PREEMPT Thu Feb 23 19:55:56 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
M2101K9AI
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

> termux-11 log

```bash
TERMUX_X11_DEBUG=1 DISPLAY=:0 termux-x11 &
[1] 12788
~ $ java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:235)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:1084)
        at android.view.ThreadedRenderer.initForSystemProcess(ThreadedRenderer.java:217)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7901)
        at com.termux.x11.Loader.main(Loader.java:37)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:363)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 19 more
Somebody connected!
New client connection!
--------- beginning of main
03-24 09:22:32.691 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:32.706 12976 12976 E Logger.TermuxSharedProperties: The style "extra-keys-style" for the key "extra-keys-style" is invalid. Using default style instead.
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: QUALCOMM build                   : c5f0e23, I9972db7aac
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Build Date                       : 04/28/21
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.10
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Local Branch                     : mybrancheba83f1e-3815-f156-b760-08f1eafda2d8
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Remote Branch                    : NONE
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
03-24 09:22:32.786 12976 13008 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
03-24 09:22:32.797 12976 13008 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
03-24 09:22:32.803 12976 12976 D SurfaceView: UPDATE null, mIsCastMode = false
03-24 09:22:32.810 12976 12976 E LorieX11Client: Surface: got new surface 0x715333c010
03-24 09:22:32.810 12976 13011 E LorieX11Client: Surface: changing surface 0x0 to 0x715333c010
03-24 09:22:32.811 12976 12976 D SurfaceView: UPDATE null, mIsCastMode = false
03-24 09:22:32.811 12976 13008 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
03-24 09:22:32.837 12976 13008 E com.termux.x11: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
03-24 09:22:32.864 12976 12976 D DecorView[]: onWindowFocusChanged hasWindowFocus true
03-24 09:22:32.910 12976 13005 I OpenGLRenderer: Davey! duration=9223362102040ms; Flags=0, FrameTimelineVsyncId=518074, IntendedVsync=9934813979489, Vsync=9934813979489, InputEventId=0, HandleInputStart=9934815818135, AnimationStart=9934815823604, PerformTraversalsStart=9934816560375, DrawStart=9934839104073, FrameDeadline=9934847312821, FrameInterval=9934815771000, FrameStartTime=16666666, SyncQueued=9934843786781, SyncStart=9934844155166, IssueDrawCommandsStart=9934844250114, SwapBuffers=9934844839646, FrameCompleted=9223372036854775807, DequeueBufferDuration=15678, QueueBufferDuration=481770, GpuCompleted=9223372036854775807, SwapBuffersCompleted=9934845647718, DisplayPresentTime=0,
03-24 09:22:33.194 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:33.696 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:34.200 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:34.705 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:35.130 12976 12976 D DecorView[]: onWindowFocusChanged hasWindowFocus false
03-24 09:22:35.180 12976 13005 I OpenGLRenderer: Davey! duration=9223362099778ms; Flags=0, FrameTimelineVsyncId=-1, IntendedVsync=9937076039957, Vsync=9937076056728, InputEventId=0, HandleInputStart=9937076094280, AnimationStart=9937076099488, PerformTraversalsStart=9937076115426, DrawStart=9937094496363, FrameDeadline=-9223372036838109143, FrameInterval=9937076056728, FrameStartTime=16666666, SyncQueued=9937111817665, SyncStart=9937111911311, IssueDrawCommandsStart=9937112223863, SwapBuffers=9937114232665, FrameCompleted=9223372036854775807, DequeueBufferDuration=32709, QueueBufferDuration=1166042, GpuCompleted=9223372036854775807, SwapBuffersCompleted=9937116078134, DisplayPresentTime=0,
03-24 09:22:35.220 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:35.586 12976 12976 E LorieX11Client: Surface: got new surface 0x0
03-24 09:22:35.586 12976 13011 E LorieX11Client: Surface: changing surface 0x715333c010 to 0x0
03-24 09:22:35.739 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
~ $ 03-24 09:22:36.258 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:36.770 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:37.281 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
03-24 09:22:37.797 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
~ $ 03-24 09:22:38.317 12976 12976 V LorieBroadcastReceiver: Extracting X connection socket.
```

**Comment by twaik** [comment]
Did you update Xwayland? Latest update broke compositor, I am already on it.

**Comment by ask9027** [comment]
Xwayland is installed from scretch also

**Comment by ask9027** [comment]
does termux-11 depend on Xwayland any more?

**Comment by twaik** [comment]
Post `Xwayland -version` output.

**Comment by ask9027** [comment]
Xwayland -version
The X.Org Foundation Xwayland Version 23.1.0 (12301000)
X Protocol Version 11, Revision 0

**Comment by twaik** [comment]
Yeah, that is latest version. I am already fixing this...

**Comment by ask9027** [comment]
#284

**Comment by highghlow** [comment]
My XWayland version is: ```
The X.Org Foundation Xwayland Version 23.1.1 (12301001) X Protocol Version 11, Revision 0
``` still have the issue
