### ISSUE TITLE
Keyboard mapping issues

### ISSUE THREAD

**Issue by zanfix** [termux/termux-x11#335]
Hi,

I am having some issues with keyboard mapping (Swiss German keyboard layout, qwertz)

With termux-x11 option "prefer scancodes" turned off:

- the key `^` and `¨` will crash termux-x11
  `^` key is between `'` and `backspace` (the last key before backspace on the numbers row)
 `"` key is between `è` and `Enter` (the last key before Enter key on the "qwertz" row)
- `AltGr` + `<` outputs `˛` instead of `backslash`
 `<` key is between `Shift_L` and `Y`

EDIT: - `CTRL` + `z` outputs `CTRL` + `y`, and `CTRL` + `y` outputs `CTRL` + `z`

With termux-x11 option "prefer scancodes" turned on:

- the key between `Shift_L` and `Y` outputs ``` instead of `<`
- `AltGr` + `<` outputs `˛` instead of `backslash`

For the AltGr + `<` one, here is the xev output:
```
KeyPress event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8456773, (-602,-77), root:(269,403),
    state 0x10, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8456911, (-602,-77), root:(269,403),
    state 0x90, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8456912, (-602,-77), root:(269,403),
    state 0x91, keycode 21 (keysym 0xfe5c, dead_ogonek), same_screen YES,
    XLookupString gives 2 bytes: (cb 9b) "˛"
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: True

KeyRelease event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8457047, (-602,-77), root:(269,403),
    state 0x91, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8457051, (-602,-77), root:(269,403),
    state 0x90, keycode 21 (keysym 0xfe53, dead_tilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
    XFilterEvent returns: False

KeyRelease event, serial 28, synthetic NO, window 0x5000001,
    root 0x38b, subw 0x0, time 8457244, (-602,-77), root:(269,403),
    state 0x90, keycode 108 (keysym 0xfe03, ISO_Level3_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 92
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
Crash dump for `^` key:
```
05-30 20:53:09.657 26827 26827 E InputEventSender: Exception dispatching finished signal.
05-30 20:53:09.657 26827 26827 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: java.lang.IllegalArgumentException
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at java.lang.Character.toChars(Character.java:5179)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at java.lang.StringFactory.newStringFromCodePoints(StringFactory.java:288)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.termux.x11.input.InputEventSender.sendKeyEvent(InputEventSender.java:183)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.termux.x11.input.TouchInputHandler.sendKeyEvent(TouchInputHandler.java:508)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.termux.x11.MainActivity.lambda$onCreate$2$com-termux-x11-MainActivity(MainActivity.java:144)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.termux.x11.MainActivity$$ExternalSyntheticLambda7.onKey(Unknown Source:4)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.View.dispatchKeyEvent(View.java:14204)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:758)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1942)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.app.Activity.dispatchKeyEvent(Activity.java:3998)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:624)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6492)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6356)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6004)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6173)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3826)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3308)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3299)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3803)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:336)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:197)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
05-30 20:53:09.658 26827 26827 E MessageQueue-JNI: 	at java.lang.reflect
05-30 20:53:09.658 26827 26827 D AndroidRuntime: Shutting down VM
--------- beginning of crash
05-30 20:53:09.659 26827 26827 E AndroidRuntime: FATAL EXCEPTION: main
05-30 20:53:09.659 26827 26827 E AndroidRuntime: Process: com.termux.x11, PID: 26827
05-30 20:53:09.659 26827 26827 E AndroidRuntime: java.lang.IllegalArgumentException
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at java.lang.Character.toChars(Character.java:5179)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromCodePoints(StringFactory.java:288)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.termux.x11.input.InputEventSender.sendKeyEvent(InputEventSender.java:183)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.termux.x11.input.TouchInputHandler.sendKeyEvent(TouchInputHandler.java:508)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.termux.x11.MainActivity.lambda$onCreate$2$com-termux-x11-MainActivity(MainActivity.java:144)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.termux.x11.MainActivity$$ExternalSyntheticLambda7.onKey(Unknown Source:4)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.View.dispatchKeyEvent(View.java:14204)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1949)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:758)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1942)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.app.Activity.dispatchKeyEvent(Activity.java:3998)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:624)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6492)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6356)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6004)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6173)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3826)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3308)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3299)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3803)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:336)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:197)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
05-30 20:53:09.659 26827 26827 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
05-30 20:53:09.674 26827 26827 I Process : Sending signal. PID: 26827 SIG: 9
```

**Comment by twaik** [comment]
@zanfix can you please check if it works?

**Comment by zanfix** [comment]
I tried build 384 but nothing changed!

**Comment by zanfix** [comment]
I had a look at logcat and:

With termux-x11 option "prefer scancodes" turned off:

- `AltGr` + `<` logs only "ViewPostIme key 0/1" messages, no text event is shown

With termux-x11 option "prefer scancodes" turned on:

- Every pressed key logs only "ViewPostIme key 0/1" messages

also TERMUX_X11_DEBUG=1 will segfault the loader immediately

**Comment by twaik** [comment]
Unfortunately Android does not let applications detect AltGr. Maybe I can make an option to generate TextEvents with right Alt key, but in this case key combinations with Right alt will stop working.

**Comment by zanfix** [comment]
On my keyboard all other combinations with AltGr already work fine. it's only the key I mentioned that do not work:

`AltGr` + `<` outputs `˛` instead of `backslash`
`<` key is between `Shift_L` and `Y`

**Comment by twaik** [comment]
I am not sure I can fix this. With my keyboard `AltGr + <` produces `×` sign with both `setxkbmap de` and `setxkbmap ch -variant de`.
