### ISSUE TITLE
I can't start ED 5in1 on the new Termux-x11 1.02.10

### ISSUE THREAD

**Issue by 3lukas3** [termux/termux-x11#356]
I can't start ED 5in1 on the new Termux-x11 1.02.10
Please help me do it

**Comment by twaik** [comment]
Post logs and detailed problem description. There are no telepaths here.

**Comment by 3lukas3** [comment]
Termux starts Termux-x11 cursor appears but no image.
`$ DISPLAY=:1 termux-x11 &                             env DISPLAY=:1 taskset -c 4-7 Xvfb -listen tcp :1 -ac -screen 0 800x480x24
[1] 9231
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.Resources.<init>(Resources.java:353)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:49)
        at android.content.res.Resources.getSystem(Resources.java:233)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:999)
        at android.app.ActivityThread.systemMain(ActivityThread.java:8108)
        at com.termux.x11.Loader.main(Loader.java:37)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:470)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        ... 17 more`

**Comment by twaik** [comment]
Cursor appearing means Termux:X11 application connected to termux-x11 server successfully. You did not start wine properly.

**Comment by twaik** [comment]
Wait. What build did you use for this? Latest server has builtin X server so Xvfb is not needed here. Start termux-x11 according to instructions in README.md.

**Comment by 3lukas3** [comment]
can add something to the shortcut?

**Comment by twaik** [comment]
Launch `termux-x11` as it is written in the instructions or contact developers of exagear mod.
