### ISSUE TITLE
java.io.FileNotFoundException: /data/system/theme_confi g/theme_compatibility.xml: open failed: ENOENT (No such fil e or directory)

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-x11#369]
[termux-report_issue_from_transcript.log](https://github.com/termux/termux-x11/files/11980042/termux-report_issue_from_transcript.log)

I used `termux-x11-nightly` and latest build version, still getting this error, this error only appears on MIUI.

Someone got the same error as me: https://t.me/termux24x7/81547/86121

**Comment by V-Official-233** [comment]
I use the latest version of Termux-x11, but still this error occurs, and this error only appears in MIUI

This is my system version
![photo_2023-07-07_17-06-42](https://github.com/termux/termux-x11/assets/104217168/9da62230-6769-43db-ad1a-f6ba606851c5)

This is the log returned by Termux
```
~ $ java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:243)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:1224)
        at android.view.ThreadedRenderer.initForSystemProcess(ThreadedRenderer.java:219)
        at android.app.ActivityThread.systemMain(ActivityThread.java:7990)
        at com.termux.x11.Loader.main(Loader.java:37)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 19 more
~ $
```
This is a reproduced video



https://github.com/termux/termux-x11/assets/104217168/a6fb0db9-0557-4594-9bf9-81b87f7bc700

**Comment by JacenBridger** [comment]
Yea, same for me MIUI android 13.

**Comment by twaik** [comment]
Not an error related to `termux-x11`. It happens because of instantiating `Context` with private API.

**Comment by twaik** [comment]
> Maybe we can fake context?

I am doing this without using reflection. https://github.com/termux/termux-x11/blob/ac7cb5a6d6dcaaf66d8d1acf377c7ba63fb5cd18/app/src/main/java/com/termux/x11/CmdEntryPoint.java#L49

**Comment by kde-yyds** [comment]
the same issue on miui14. but it's a warning and termux-x11 runs normally
