### ISSUE TITLE
"No package identifier when getting value for resource number 0x000600a6"

### ISSUE THREAD

**Issue by fuger222** [termux/termux-x11#426]
Seems to be related to issue #413 
When I try to run `termux-x11 :1`, it dies from a SIGKILL without any error message. I'm using Android 8 / Oreo, and the latest Termux (Build #646: Commit 7c262b8) and Termux X11 (Build #482: Commit 8d98883) packages from Github.

<details>

```
08-16 11:22:00.167 16303 16303 D AndroidRuntime: Calling main entry com.termux.x11.Loader
08-16 11:22:00.168 16303 16303 I Termux:X11 loader: started
08-16 11:22:00.182 16312 16312 E asset   : setgid: Operation not permitted
08-16 11:22:00.216 16314 16314 E asset   : setgid: Operation not permitted
08-16 11:22:00.239 16303 16303 E asset   : AssetManager::addSystemOverlays delete oidmap
08-16 11:22:00.242 16303 16303 E asset   : AssetManager::addSystemOverlays delete oidmap
08-16 11:22:00.260 16303 16303 W ResourceType: No package identifier when getting value for resource number 0x000600a6
08-16 11:22:00.260 16303 16303 D AndroidRuntime: Shutting down VM
08-16 11:22:00.269 16303 16303 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
08-16 11:22:00.269 16303 16303 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate Application():android.content.res.Resources$NotFoundException: Resource ID #0x600a6
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityThread.attach(ActivityThread.java:6632)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityThread.systemMain(ActivityThread.java:6672)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at com.termux.x11.Loader.main(Loader.java:50)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x600a6
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:223)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.content.res.Resources.getBoolean(Resources.java:1065)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at com.lge.systemservice.core.PerfTrackerManager.init(PerfTrackerManager.java:49)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.Application.onCreate(Application.java:103)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityThread.attach(ActivityThread.java:6630)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	... 4 more
08-16 11:22:00.269 16303 16303 E AndroidRuntime: Error reporting crash
08-16 11:22:00.269 16303 16303 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:766)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:56)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4425)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4423)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4418)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
08-16 11:22:00.269 16303 16303 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
08-16 11:22:00.269 16303 16303 I Process : Sending signal. PID: 16303 SIG: 9
```
</details>

**Comment by twaik** [comment]
It looks like that is some device-related bug, I am not sure if it can be fixed.

**Comment by twaik** [comment]
Because it must pass Binder to BroadcastReceiver which is impossible while using `am` command.

**Comment by twaik** [comment]
I can try to invoke some private Android APIs to let it work without instantiating Context, but it may be a bit problematic.

**Comment by twaik** [comment]
Can you please post `termux-info` output?

**Comment by twaik** [comment]
Try to replace `/data/data/com.termux/files/usr/libexec/termux-x11/loader.apk` with the apk inside this zip archive.

[shell-loader-debug.zip](https://github.com/termux/termux-x11/files/12359618/shell-loader-debug.zip)

**Comment by twaik** [comment]
Is this log relevant to your version of loader or to the version I've sent you?

**Comment by twaik** [comment]
Unfortunately I have no idea how to fix this. That is some firmware-related bug. And I do not have source codes of this to fix.

**Comment by twaik** [comment]
Wait a sec.

**Comment by twaik** [comment]
This one should be better.
[shell-loader-debug.zip](https://github.com/termux/termux-x11/files/12361670/shell-loader-debug.zip)

**Comment by twaik** [comment]
Ok, wait. I've got this.

**Comment by twaik** [comment]
[shell-loader-debug.zip](https://github.com/termux/termux-x11/files/12361760/shell-loader-debug.zip)

**Comment by twaik** [comment]
Aaand the main package:
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12361853/app-arm64-v8a-debug.zip)

**Comment by twaik** [comment]
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12362006/app-arm64-v8a-debug.zip)

**Comment by twaik** [comment]
Ok, I am merging it. The issue will be closed with a commit.

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/actions/runs/5882099400

**Comment by twaik** [comment]
Can you please test latest loader? I changed it's code again.
