### ISSUE TITLE
Termux X11 cannot run on Xiaomi Pad 6 Pro

### ISSUE THREAD

**Issue by bamboofeng** [termux/termux-x11#468]
MIUI Version: MIUI Pad 14.0.9
Android Version: 13

~ $ termux-x11

java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:251)
        at android.app.LoadedApk.<init>(LoadedApk.java:253)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:3062)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2854)
        at com.termux.x11.Loader.createContext(Loader.java:135)
        at com.termux.x11.Loader.main(Loader.java:52)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 20 more
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

**Comment by twaik** [comment]
1. You are using outdated loader.
2. There is another active process of `termux-x11`. You should reboot your device and try again.

**Comment by bamboofeng** [comment]
> 1. You are using outdated loader.
> 2. There is another active process of `termux-x11`. You should reboot your device and try again.

x11-repo version: 8.4-1
termux-x11-nightly: 1.03.00-2
Here is my current loader version, but I still cannot run termux-x11, and it also doesn't work after a reboot. Below is the log file.

[x11_debug_log.txt](https://github.com/termux/termux-x11/files/12707026/x11_debug_log.txt)

**Comment by twaik** [comment]
`pkg up && apt upgrade termux-x11-nightly`.

**Comment by twaik** [comment]
Actually your debug log shows that it works normally. Did you start Termux:X11 activity?

**Comment by bamboofeng** [comment]
Running xfce4 also has errors, and initially, I thought the "No such file or directory" error from termux-x11 was the key issue, but it seems that there is an issue with xfce4. I cannot confirm at the moment.

```
(xfwm4:6238): xfwm4-WARNING **: 18:54:57.554: Unsupported GL renderer (llvmpipe (LLVM 15.0.6, 128 bits)).

(xfsettingsd:6308): libupower-glib-WARNING **: 18:54:57.651: Couldn't connect to proxy: Could not connect: No such file or directory

** (agent:6351): CRITICAL **: 18:54:58.361: Failed to get connection to system bus: Could not connect: No such file or directory

** (xiccd:6347): CRITICAL **: 18:54:58.366: Failed to connect to colord: Could not connect: No such file or directory
Failure: Module initialization failed
libclock-Message: 18:54:58.501: could not get proxy for org.freedesktop.login1

(xfce4-panel:6313): libclock-WARNING **: 18:54:58.503: could not instantiate a sleep monitor

(polkit-gnome-authentication-agent-1:6375): polkit-gnome-1-WARNING **: 18:54:58.560: Error getting authority: Error initializing authority: Could not connect: No such file or directory

** (light-locker:6348): ERROR **: 18:54:58.561: session_id is not set, is /proc mounted with hidepid>0?
Xlib:  extension "DPMS" missing on display ":0.0".

(xfce4-power-manager:6342): xfce4-power-manager-WARNING **: 18:54:58.602: Monitor is not DPMS capable

(xfce4-power-manager:6342): GLib-GIO-CRITICAL **: 18:54:58.605: g_dbus_connection_signal_subscribe: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(xfce4-power-manager:6342): libupower-glib-WARNING **: 18:54:58.854: Couldn't connect to proxy: Could not connect: No such file or directory

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.879: Error getting system bus connection : Could not connect: No such file or directory

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.880: xfpm_polkit_check_auth_intern: assertion 'polkit->priv->proxy != NULL' failed

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.880: xfpm_polkit_check_auth_intern: assertion 'polkit->priv->proxy != NULL' failed

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.881: xfpm_polkit_check_auth_intern: assertion 'polkit->priv->proxy != NULL' failed

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.881: xfpm_polkit_check_auth_intern: assertion 'polkit->priv->proxy != NULL' failed

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.881: Unable to connect to the system bus : Could not connect: No such file or directory

(xfce4-power-manager:6342): xfce4-power-manager-WARNING **: 18:54:58.885: could not map keysym 1008ffa8 to keycode


(xfce4-power-manager:6342): xfce4-power-manager-WARNING **: 18:54:58.886: Unable connect to system bus: Could not connect: No such file or directory

** (xfce4-power-manager:6342): WARNING **: 18:54:58.887: No outputs have backlight property

** (xfpm-power-backlight-helper:6425): WARNING **: 18:54:58.905: failed to find any devices: Error opening directory ?/sys/class/backlight?: Permission denied

(xfce4-power-manager:6342): xfce4-power-manager-CRITICAL **: 18:54:58.906: Unable to get system bus connection : Could not connect: No such file or directory

** (wrapper-2.0:6359): WARNING **: 18:54:59.207: No outputs have backlight property

** (xfpm-power-backlight-helper:6438): WARNING **: 18:54:59.218: failed to find any devices: Error opening directory ?/sys/class/backlight?: Permission denied

(wrapper-2.0:6359): libupower-glib-WARNING **: 18:54:59.223: Couldn't connect to proxy: Could not connect: No such file or directory

(wrapper-2.0:6359): GLib-GObject-WARNING **: 18:54:59.240: invalid (NULL) pointer instance

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.240: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:6359): GLib-GObject-WARNING **: 18:54:59.241: invalid (NULL) pointer instance

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.241: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:54:59.307: up_device_get_object_path: assertion 'UP_IS_DEVICE (device)' failed

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.307: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(wrapper-2.0:6359): GLib-GObject-WARNING **: 18:54:59.307: invalid (NULL) pointer instance

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.308: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.308: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:54:59.308: up_device_get_object_path: assertion 'UP_IS_DEVICE (device)' failed

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:54:59.309: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:54:59.309: up_client_get_lid_is_present: assertion 'UP_IS_CLIENT (client)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:54:59.310: up_client_get_on_battery: assertion 'UP_IS_CLIENT (client)' failed

(wrapper-2.0:6422): libactions-WARNING **: 18:54:59.315: Calling CanShutdown failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(wrapper-2.0:6422): libactions-WARNING **: 18:54:59.348: Calling CanRestart failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(xfce4-session:6139): xfce4-session-WARNING **: 18:54:59.366: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:6139): xfce4-session-WARNING **: 18:54:59.384: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:6139): xfce4-session-WARNING **: 18:54:59.406: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(wrapper-2.0:6359): GLib-GObject-CRITICAL **: 18:55:00.383: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:55:00.384: up_client_get_lid_is_present: assertion 'UP_IS_CLIENT (client)' failed

(wrapper-2.0:6359): libupower-glib-CRITICAL **: 18:55:00.384: up_client_get_on_battery: assertion 'UP_IS_CLIENT (client)' failed

(wrapper-2.0:6352): pulseaudio-plugin-WARNING **: 18:55:01.086: Disconnected from the PulseAudio server. Attempting to reconnect in 5 seconds...

Hangup

[Process completed (signal 9) - press Enter]
```

**Comment by twaik** [comment]
These errors are related to your environment, not to `termux-x11`.

**Comment by bamboofeng** [comment]
Thank you, I'll check my environment.
