### ISSUE TITLE
[Bug]: always make proot-distro crashed

### ISSUE THREAD

**Issue by northgreen** [termux/termux-x11#482]
### Problem description

termux x11 may have a bug ,it always make proot-distro crashed

### What steps will reproduce the bug?

first：
`~ $ proot-distro login --user ictye ubuntu --shared-tmp `
And then after a while it will collapse for no reason......
only execute `/usr/share/code/code --unity-launch --no-sandbox %F`

`sudo apt install git`

`sudo apt upgrade`

### What is the expected behavior?

日志：

```

Welcome to Termux!

Docs:       https://termux.dev/docs
Donate:     https://termux.dev/donate
Community:  https://termux.dev/community

Working with packages:

 - Search:  pkg search <query>
 - Install: pkg install <package>
 - Upgrade: pkg upgrade

Subscribing to additional repositories:

 - Root:    pkg install root-repo
 - X11:     pkg install x11-repo

For fixing any repository issues,
try 'termux-change-repo' command.

Report issues at https://termux.dev/issues
~ $ proot-distro login --user ictye ubuntu --shared-tmp --termux-home
ictye@localhost:~$ termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(ThemeCompatibility.java:111)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:243)
        at android.app.LoadedApk.<init>(LoadedApk.java:257)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:3063)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2832)
        at com.termux.x11.Loader.createContext(Loader.java:135)
        at com.termux.x11.Loader.main(Loader.java:52)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:387)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 20 more
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root

(xfwm4:23586): xfwm4-WARNING **: 07:52:24.633: Unsupported GL renderer (llvmpipe (LLVM 15.0.7, 128 bits)).

(xfsettingsd:23609): libupower-glib-WARNING **: 07:52:25.194: Couldn't connect to proxy: Could not connect: No such file or directory

(xfsettingsd:23609): xfsettingsd-WARNING **: 07:52:25.232: Unknown mode '1080x2316 @ 60.0' for output screen, aborting.

** (xiccd:23637): CRITICAL **: 07:52:28.215: Failed to connect to colord: Could not connect: No such file or directory
Connection failure: Connection refused

(polkit-gnome-authentication-agent-1:23657): polkit-gnome-1-WARNING **: 07:52:28.518: Error getting authority: Error initializing authority: Could not connect: No such file or directory

** (xfce4-screensaver:23636): WARNING **: 07:52:28.640: screensaver already running in this session

(xfdesktop:23621): GVFS-RemoteVolumeMonitor-WARNING **: 07:52:28.697: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(xfdesktop:23621): thunar-uca-WARNING **: 07:52:28.919: Unknown element ignored: <submenu>

(xfdesktop:23621): thunar-uca-WARNING **: 07:52:28.919: Unknown element ignored: <range>

(wrapper-2.0:23625): GLib-GIO-CRITICAL **: 07:52:28.975: g_file_new_for_path: assertion 'path != NULL' failed

(wrapper-2.0:23625): GLib-GIO-CRITICAL **: 07:52:28.976: g_file_monitor_file: assertion 'G_IS_FILE (file)' failed

(wrapper-2.0:23625): GLib-GObject-WARNING **: 07:52:28.976: invalid (NULL) pointer instance

(wrapper-2.0:23625): GLib-GObject-CRITICAL **: 07:52:28.977: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(wrapper-2.0:23625): Gtk-WARNING **: 07:52:28.978: Attempting to add a widget with type GtkToggleButton to a container of type XfcePanelPlugin, but the widget is already inside a container of type XfcePanelPlugin, please remove the widget from its existing container first.

(wrapper-2.0:23635): libactions-WARNING **: 07:52:29.094: Calling CanShutdown failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(wrapper-2.0:23635): libactions-WARNING **: 07:52:29.100: Calling CanRestart failed GDBus.Error:org.xfce.SessionManager.Error.Failed: Could not connect: No such file or directory

(xfce4-session:23537): xfce4-session-WARNING **: 07:52:29.110: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(xfce4-session:23537): xfce4-session-WARNING **: 07:52:29.123: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

** (xfdesktop:23621): WARNING **: 07:52:29.127: Failed to get system bus: Could not connect: No such file or directory

(xfce4-session:23537): xfce4-session-WARNING **: 07:52:29.136: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

(wrapper-2.0:23625): Gtk-WARNING **: 07:52:29.255: Negative content width -3 (allocation 1, extents 2x2) while allocating gadget (node button, owner GtkToggleButton)

(wrapper-2.0:23635): Gtk-WARNING **: 07:52:29.301: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner XfceArrowButton)
[24106:1012/075320.746200:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[24107:1012/075320.746284:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[24102:1012/075320.783987:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[24102:1012/075321.194544:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[24102:1012/075321.194694:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[24102:1012/075321.206648:ERROR:address_tracker_linux.cc(225)] Could not bind NETLINK socket: Permission denied (13)
[24102:1012/075321.207110:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[24102:1012/075321.282451:ERROR:udev_watcher.cc(52)] Failed to initialize a udev monitor.
pcilib: Cannot open /proc/bus/pci/devices
[24146:1012/075321.372135:ERROR:file_path_watcher_inotify.cc(822)] Failed to read /proc/sys/fs/inotify/max_user_watches
[24102:1012/075321.386218:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[24102:1012/075321.489297:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[24102:1012/075321.506825:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[24102:1012/075321.506969:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[24102:1012/075321.507115:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[main 2023-10-12T07:53:21.652Z] update#setState idle
[24102:1012/075321.773831:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[24102:1012/075322.248299:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[24102:1012/075322.562563:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[24102:1012/075322.713752:ERROR:gpu_process_host.cc(958)] GPU process exited unexpectedly: exit_code=256
[main 2023-10-12T07:53:51.663Z] update#setState checking for updates
[main 2023-10-12T07:53:51.880Z] update#setState idle

[Process completed (signal 9) - press Enter]
```

**Comment by twaik** [comment]
1. You have outdated `termux-x11-nightly` package.
2. Most likely that is problem of distro installed with `proot-distro`.
3. `signal 9` may mean you ran out of memory. There is no fix for this.

**Comment by northgreen** [comment]
> 1. You have outdated `termux-x11-nightly` package.
> 2. Most likely that is problem of distro installed with `proot-distro`.
> 3. `signal 9` may mean you ran out of memory. There is no fix for this.

thanks
