### ISSUE TITLE
[Bug]: process gets killed on s23 with oneui6 android 14

### ISSUE THREAD

**Issue by nightshade427** [termux/termux-x11#502]
### Problem description

process gets killed on s23 with oneui6 android 14

Simply says "killed" even when logging is turned on using 'TERMUX_X11_DEBUG=1 termux-x11 :0'

### What steps will reproduce the bug?

TERMUX_X11_DEBUG=1 termux-x11 :0

**Comment by twaik** [comment]
Run `logcat` in termux and post here the log.

**Comment by nightshade427** [comment]
AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<                                       16 11-21 02:06:44.757 12480 12480 I AndroidRuntime: Using default boot image                                                                            17 11-21 02:06:44.757 12480 12480 I AndroidRuntime: Leaving lock profiling enabled                                                                      18 11-21 02:06:44.757 12480 12480 W libc    : Access denied finding property "odsign.verification.success"                                              19 11-21 02:06:44.760 12480 12480 D AndroidRuntime: addProductProperty not brand or 7                                                                   20 11-21 02:06:44.764 12480 12480 W app_process: ART APEX data files are untrusted.                                                                     21 11-21 02:06:44.764 12480 12480 I app_process: Using CollectorTypeCC GC.                                                                              22 11-21 02:06:44.767 12480 12480 E app_process: Error reading named image component header for /system/framework/boot.art, error: Failed to open oat   23 11-21 02:06:44.767 12480 12480 E app_process: Could not create image space with image file '/system/framework/boot.art!/apex/com.android.art/etc/bo  24 11-21 02:06:44.988 12480 12480 W app_process: Skipping non-existent dex file '/apex/com.samsung.android.ipm/javalib/framework-samsung-ipm.jar'       25 11-21 02:06:44.989 12480 12480 W app_process: Skipping non-existent dex file '/apex/com.samsung.android.shell/javalib/framework-samsung-privilege.j  26 11-21 02:06:45.006 12480 12480 D nativeloader: InitDefaultPublicLibraries for_preload=1: libandroid.so:libaaudio.so:libamidi.so:libbinder_ndk.so:li  27 11-21 02:06:45.029 12480 12480 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
  28 11-21 02:06:45.030 12480 12480 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt72l.dat
  29 11-21 02:06:45.069 12480 12480 W ziparchive: Unable to open '/data/data/com.termux/files/usr/libexec/termux-x11/loader.dm': No such file or directo
  30 11-21 02:06:45.153 12480 12480 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
  31 11-21 02:06:45.153 12480 12480 E SemAffinityControl: SemAffinityControl: registerfunction enter
  32 11-21 02:06:45.183 12480 12480 W libc    : Access denied finding property "ro.product.name_for_attestation"
  33 11-21 02:06:45.183 12480 12480 W libc    : Access denied finding property "ro.product.brand_for_attestation"
  34 11-21 02:06:45.183 12480 12480 W libc    : Access denied finding property "ro.product.model_for_attestation"
  35 11-21 02:06:45.191 12480 12480 D AndroidRuntime: Calling main entry com.termux.x11.Loader
  36 11-21 02:06:45.193 12480 12480 I Termux:X11 loader: started
  37 11-21 02:06:45.204 12480 12480 W libc    : Access denied finding property "qemu.sf.lcd_density"
  38 11-21 02:06:45.204 12480 12480 W libc    : Access denied finding property "qemu.sf.lcd_density"
  39 11-21 02:06:45.316 12480 12480 W app_process: unable to execute idmap2: Permission denied
  40 11-21 02:06:45.317 12480 12480 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
  41 11-21 02:06:45.318 12480 12480 W libc    : Access denied finding property "ro.vendor.mtk_model"
  42 11-21 02:06:45.340 12480 12480 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
  43 11-21 02:06:45.347 12480 12480 E SystemServiceRegistry: SemDisplayQualityFeature.ENABLED:false,PLATFORM:
  44 11-21 02:06:45.349 12480 12480 W app_process: Landroid/app/SystemServiceRegistry; failed initialization: java.lang.NoClassDefFoundError: Class not
  45 11-21 02:06:45.349 12480 12480 W app_process: (Throwable with no stack trace)
  46 11-21 02:06:45.350 12480 12480 D AndroidRuntime: Shutting down VM
  47 11-21 02:06:45.351 12480 12480 E AndroidRuntime: FATAL EXCEPTION: main
  48 11-21 02:06:45.351 12480 12480 E AndroidRuntime: PID: 12480
  49 11-21 02:06:45.351 12480 12480 E AndroidRuntime: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace availa
  50 11-21 02:06:45.357 12480 12480 E AndroidRuntime: Error reporting crash
  51 11-21 02:06:45.357 12480 12480 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
  52 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
  53 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:662)
  54 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:443)
  55 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
  56 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:437)
  57 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:206)
  58 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.app.ActivityManager$3.create(ActivityManager.java:5614)
  59 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.app.ActivityManager$3.create(ActivityManager.java:5611)
  60 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:43)
  61 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:5602)
  62 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit
  63 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
  64 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
  65 11-21 02:06:45.357 12480 12480 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
  66 11-21 02:06:45.357 12480 12480 I Process : Sending signal. PID: 12480 SIG: 9
  67 11-21 02:06:46.437 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: MSG_WINDOW_TOUCH_MODE_CHANGED
  68 11-21 02:06:47.130 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 0
  69 11-21 02:06:47.130 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 0
  70 11-21 02:06:47.130 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 1
  71 11-21 02:06:47.130 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 1
  72 11-21 02:06:47.150 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: onDisplayChanged oldDisplayState=2 newDisplayState=2
  73 11-21 02:06:47.155 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: onDisplayChanged oldDisplayState=2 newDisplayState=2
  74 11-21 02:06:49.732 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 0
  75 11-21 02:06:49.732 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 0
  76 11-21 02:06:49.732 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 1
  77 11-21 02:06:49.732 10507 10507 I ViewRootImpl@2ed1d71[TermuxActivity]: ViewPostIme key 1

**Comment by twaik** [comment]
Are you trying to start it as root or something?

**Comment by twaik** [comment]
Try to start it outside of proot-distro and start your proot-distro environment with `--shared-tmp`.

**Comment by nightshade427** [comment]
That works! Thanks! 

It's weird though, I used to be able to start it from inside a proot.
https://github.com/termux/termux-x11#using-with-proot-environment

**Comment by twaik** [comment]
You should open issue in proot-distro repo.
