### ISSUE TITLE
[Bug]: unable to exec termux-x11 :1 command

### ISSUE THREAD

**Issue by ArcheyChen** [termux/termux-x11#518]
### Problem description

unable to run termux-x11 on a fresh install of termux.
``ˋbash
~ $ TERMUX_X11_DEBUG=1 termux-x11 :0
java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:403)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ActivityThread.getConfiguration()' on a null object reference
        at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:189)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:39)
        ... 5 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.app.ActivityThread.getConfiguration()' on a null object reference
        at android.view.Display.getMetrics(Display.java:1154)                                                                                        at android.app.ResourcesManager.getDisplayMetrics(ResourcesManager.java:256)
        at android.app.ResourcesManager.getDisplayMetrics(ResourcesManager.java:244)
        at android.app.ContextImpl.createSystemContext(ContextImpl.java:2640)
        at android.app.ActivityThread.getSystemContext(ActivityThread.java:2571)
        at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:187)                                                                        ... 6 more
~ $
ˋˋˋ

### What steps will reproduce the bug?

Device: Lenovo Y700(2022)
OS ver:13.1.578
Base on Android 11

termux download from github

install x11-repo and termux-x11-nightly

**Comment by twaik** [comment]
This error is caused by changes made by Lenovo in firmware of your device. Unfortunately I can not fix this.

**Comment by ArcheyChen** [comment]
> This error is caused by changes made by Lenovo in firmware of your device. Unfortunately I can not fix this.

I just updated my OS to ZUI 14 and it works fine on it. 
just in case someone have same problem

**Comment by rasp0wn** [comment]
I will update my tablet to make it work, thank you!
