### ISSUE TITLE
Error: java.lang.UnsatisfiedLinkError: dlopen failed: library "liblorie.so" not found

### ISSUE THREAD

**Issue by asve79** [termux/termux-x11#525]
### Problem description

Error, when starting termux-x11

java.lang.UnsatisfiedLinkError: dlopen failed: library "liblorie.so" not found

### What steps will reproduce the bug?

~ $ pkg in x11-repo && pkg in termux-x11-nightly
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
x11-repo is already the newest version (8.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking availability of current mirror:
[*] https://packages-cf.termux.dev/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
termux-x11-nightly is already the newest version (1.03.00-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
~ $ termux-x11
java.lang.UnsatisfiedLinkError: dlopen failed: library "liblorie.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:237)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:376)

**Comment by twaik** [comment]
Install apk from the following source: https://github.com/termux/termux-x11/releases/tag/nightly
Old versions are not supported.

**Comment by asve79** [comment]
Ok, thank you, but didn't work.. (

==
~ $ apt install ./termux-x11-nightly-1.03.00-0-all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'termux-x11-nightly' instead of './termux-x11-nightly-1.03.00-0-all.deb'
The following NEW packages will be installed:
  termux-x11-nightly
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4722 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /data/data/com.termux/files/home/termux-x11-nightly-1.03.00-0-all.deb termux-x11-nightly all 1.03.00-0 [4722 B]
Selecting previously unselected package termux-x11-nightly.
(Reading database ... 68443 files and directories currently installed.)
Preparing to unpack .../termux-x11-nightly-1.03.00-0-all.deb ...
Unpacking termux-x11-nightly (1.03.00-0) ...
Setting up termux-x11-nightly (1.03.00-0) ...

~ $ termux-x11
java.lang.UnsatisfiedLinkError: dlopen failed: library "liblorie.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:237)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:376)

==

**Comment by twaik** [comment]
Install **apk** from there.
