### ISSUE TITLE
[Bug]: termux-11 call 

### ISSUE THREAD

**Issue by T0n0T** [termux/termux-x11#551]
### Problem description

When I enter any command that includes **`termux-x11`**, I receive the following log.
- termux package and application are both the latest version. 
- has tried [Nightly Release 20231006](https://github.com/termux/termux-x11/releases/tag/nightly)
- has tried [Nightly Release 20231006](https://github.com/termux/termux-x11/actions/runs/7704347161)

```shell
❯ termux-x11
java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:389)
Caused by: java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:116)
        at android.os.Looper.prepareMainLooper(Looper.java:130)
        at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:221)
        ... 5 more
```
**`termux-info`**:
```shell
❯ termux-info
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=26002
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.40.5
Android version:
12
Kernel build information:
Linux localhost 5.10.66-android12-9-g3b603a896f94 #1 SMP PREEMPT Tue Dec 13 13:43:21 UTC 2022 aarch64 Android
Device manufacturer:
HONOR
Device model:
ROD-W09
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
```

### What steps will reproduce the bug?

just enter any command that includes **`termux-x11`**

**Comment by twaik** [comment]
Install both *.apk and *.deb from the same source.

**Comment by T0n0T** [comment]
> Install both *.apk and *.deb from the same source.

I has tried to use same source before the issue,like what you said here #508.
However,it doesn't work. Perhaps it's the manufacturer's fault?

**Comment by twaik** [comment]
No. It means you are using outdated `deb` with recent `apk`. There is no other reason why this error can appear.

**Comment by twaik** [comment]
@T0n0T can you please check the artifact from https://github.com/termux/termux-x11/actions/runs/8281544014 ?
