### ISSUE TITLE
[Bug]: black screen with no cursor

### ISSUE THREAD

**Issue by yueziji** [termux/termux-x11#560]
### Problem description

[](url)only black screen with no cursor...but can touch.
i use TERMUX_X11_DEBUG=1 to start and found this log.

```
02-18 14:04:12.375 15014 15030 E Surface : Exception creating surface from parcel
02-18 14:04:12.375 15014 15030 E Surface : java.lang.RuntimeException: Can't create handler inside thread Thread[Binder:15014_3,5,main] that has not called Looper.prepare()
02-18 14:04:12.375 15014 15030 E Surface :      at android.os.Handler.<init>(Handler.java:207)
02-18 14:04:12.375 15014 15030 E Surface :      at android.os.Handler.<init>(Handler.java:119)
02-18 14:04:12.375 15014 15030 E Surface :      at com.meizu.nightmode.MzNightModeManager.<init>(MzNightModeManager.java:180)
02-18 14:04:12.375 15014 15030 E Surface :      at com.meizu.nightmode.MzNightModeManager.getDefault(MzNightModeManager.java:382)
02-18 14:04:12.375 15014 15030 E Surface :      at android.graphics.BaseCanvas.<init>(BaseCanvas.java:1027)
02-18 14:04:12.375 15014 15030 E Surface :      at android.graphics.Canvas.<init>(Canvas.java:97)
02-18 14:04:12.375 15014 15030 E Surface :      at android.view.Surface$CompatibleCanvas.<init>(Surface.java:879)
02-18 14:04:12.375 15014 15030 E Surface :      at android.view.Surface$CompatibleCanvas.<init>(Surface.java:879)
02-18 14:04:12.375 15014 15030 E Surface :      at android.view.Surface.<init>(Surface.java:120)
02-18 14:04:12.375 15014 15030 E Surface :      at android.view.Surface$1.createFromParcel(Surface.java:93)
02-18 14:04:12.375 15014 15030 E Surface :      at android.view.Surface$1.createFromParcel(Surface.java:89)
02-18 14:04:12.375 15014 15030 E Surface :      at com.termux.x11.ICmdEntryInterface$_Parcel.readTypedObject(ICmdEntryInterface.java:178)
02-18 14:04:12.375 15014 15030 E Surface :      at com.termux.x11.ICmdEntryInterface$_Parcel.access$000(ICmdEntryInterface.java:173)
02-18 14:04:12.375 15014 15030 E Surface :      at com.termux.x11.ICmdEntryInterface$Stub.onTransact(ICmdEntryInterface.java:73)
02-18 14:04:12.375 15014 15030 E Surface :      at android.os.Binder.execTransactInternal(Binder.java:1027)
02-18 14:04:12.375 15014 15030 E Surface :      at android.os.Binder.execTransact(Binder.java:1000)
```

### What steps will reproduce the bug?

After entering termux-x11-nightly, there is only a black screen and no x cursor in termux:x11.

### What is the expected behavior?

Normal display screen.

**Comment by twaik** [comment]
Seeing black screen with cursor means X server started successfully, but you did not start any X client.

**Comment by yueziji** [comment]
but i cannot see anything include x cursor,other x client can start normally but it still see nothing.
I have compiled many versions of deb packages. The deb packages before [https://github.com/termux/termux-x11/commit/f8c8cacab481503988a340c8c2d62e3e472b7755](url) can display normally.

**Comment by twaik** [comment]
Unfortunately I can not revert this. Reverting will break compatibility for other device.

**Comment by twaik** [comment]
Ok, I can not revert this, but can add an option to instantiate Context in old way with environment variable.
Check [build 594](https://github.com/termux/termux-x11/actions/runs/8431417771).
Try `OLD_CONTEXT=1 termux-x11 :0 -xstartup xfce4-session`.

**Comment by yueziji** [comment]
It still doesn't work normally, it's very strange...

**Comment by twaik** [comment]
Try **this build** please.

**Comment by yueziji** [comment]
It is working perfectly now, thank you very much!
