### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by licryle** [termux/termux-x11#582]
### Problem description

I've followed the instructions from [Termux_XFCE](https://github.com/phoenixbyrd/Termux_XFCE), and upon starting, it crashes X11 with an internal error.

Note that the X11 apk does start, but on an empty window.
This bug was also posted here https://github.com/phoenixbyrd/Termux_XFCE/issues/36

```
java.lang.ExceptionInInitializerError at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:536) at com.termux.x11.Loader.main(Loader.java:24)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:402)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Can't create handler inside thread Thread[main,10,main] that has not called Looper.prepare()
 at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:180)
 at com.termux.x11.CmdEntryPoint.<clinit>(CmdEntryPoint.java:39) ... 5 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[main,10,main] that has not called Looper.prepare()
 at android.os.Handler.<init>(Handler.java:261)
 at android.app.ResourcesManager$1.<init>(ResourcesManager.java:153)
 at android.app.ResourcesManager.<init>(ResourcesManager.java:153)
 at android.app.ResourcesManager.getInstance(ResourcesManager.java:332)
 at android.app.ContextImpl.<init>(ContextImpl.java:3664)
 at android.app.ContextImpl.createSystemContext(ContextImpl.java:3465)
 at android.app.ActivityThread.getSystemContext(ActivityThread.java:3621)
 at com.termux.x11.CmdEntryPoint.createContext(CmdEntryPoint.java:178)
 ... 6 more
xfce4-session: Cannot open display: . Type 'xfce4-session --help' for usage.    
```

### What steps will reproduce the bug?

Install [Termux_XFCE](https://github.com/phoenixbyrd/Termux_XFCE), run "start".

**Comment by twaik** [comment]
Old apks and debs are not supported. Download new versions from https://github.com/termux/termux-x11/releases/tag/nightly .

**Comment by twaik** [comment]
Duplicate of #568 .
