### ISSUE TITLE
[Bug]: triggered 'if (!mouse->ptrfeed)'

### ISSUE THREAD

**Issue by high20212021** [termux/termux-x11#616]
### Problem description

java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:109)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at com.termux.x11.CmdEntryPoint.lambda$spawnListeningThread$1(CmdEntryPoint.java:144)
        at com.termux.x11.CmdEntryPoint.$r8$lambda$ViPcpFnEzoJCKyl-YNiduQ0Vo1o(CmdEntryPoint.java:0)
        at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)
        at libcore.io.IoBridge.bind(IoBridge.java:105)
        ... 8 more
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
** Message: 07:53:00.206: main.vala:102: Session is (null)
** Message: 07:53:00.217: main.vala:103: DE is (null)
** Message: 07:53:00.218: main.vala:107: No session set, fallback to LXDE session
** Message: 07:53:00.218: main.vala:113: No desktop environnement set, fallback to LXDE
** Message: 07:53:00.265: main.vala:134: log directory: /home/yukati/.cache/lxsession/LXDE
** Message: 07:53:00.265: main.vala:135: log path: /home/yukati/.cache/lxsession/LXDE/run.log
(EE) BUG: triggered 'if (!mouse->ptrfeed)'
(EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/dix/devices.c:2288 in ProcChangePointerControl()

### What steps will reproduce the bug?

install proot-distro with:
ArchLinux,zh_CN.utf-8 locale
LXDE
and touch a specific place

**Comment by twaik** [comment]
> Cannot establish any listening sockets - Make sure an X server isn't already running

That message means X server already runs somewhere in background.

**Comment by twaik** [comment]
Are you using direct touchscreen mode or something?

**Comment by high20212021** [comment]
yes

**Comment by high20212021** [comment]
and i stopped the x server
but it cannot run again now
