### ISSUE TITLE
libXlorie.so

### ISSUE THREAD

**Issue by Arsenii888** [termux/termux-x11#700]
Sorry for the question, but I can't open the compiled termux x11 error looks like this:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.termux-zBJbtGQnm1ICqIjud1NJBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.termux-zBJbtGQnm1ICqIjud1NJBw==/lib/arm, /data/app/com.termux-zBJbtGQnm1ICqIjud1NJBw==/base.apk!/lib/armeabi-v7a, /system/lib]]] couldn't find "libXlorie.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1669)
                                                                                                    	at com.termux.x11.LorieView.<clinit>(LorieView.java:379)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
                                                                                                    	at com.termux.x11.MainActivity.onCreate(MainActivity.java:160)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7144)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7135)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3083)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6671)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

**Comment by twaik** [comment]
Did you install correct termux-x11 version? Try the universal build.

**Comment by Arsenii888** [comment]
The universal apk from the releases does not help, but it seems that this problem does not occur only on the Redmi 6a (android 9) smartphone. 
When I try to compile x11 myself I get the same error

**Comment by twaik** [comment]
It seems like it is some weird firmware related quirk.

**Comment by Arsenii888** [comment]
So what is libXlorie.so in x11 source code?
(this is my last question)

**Comment by Biswa96** [comment]
> So what is libXlorie.so in x11 source code?

https://github.com/termux/termux-x11/blob/d366d40e5cc290890f70a8949ae604bef8975518/app/src/main/cpp/recipes/xserver.cmake#L263

**Comment by Arsenii888** [comment]
Thank
