### ISSUE TITLE
[Bug]: Termux X11 crashes when keyboard disconnects

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#765]
### Problem description

This may be related to KeyInterceptor. In short, up to 3 devices can be connected in a Logitech keyboard. If I switch the keyboard to another computer, try to go back, etc. then it may happen that Termux X11 scrash. Just connect back (by clicking the icon), however, it is nice if the bug is fixed

```
12-09 19:53:24.243 12775 12775 D DEVICES     : found device "kona-wcd9380-awinic-snd-card Headset Jack" sources 0x80000101
12-09 19:53:24.243 12775 12775 D DEVICES     : found device "C-Media Electronics Inc. USB Audio Device" sources 0x00000101
12-09 19:53:24.243 12775 12775 D DEVICES     : found device "STMicroelectronics Composite HID Keyboard and Touchpad Keyboard" external keyboard sources 0x00000101
12-09 19:53:24.243 12775 12775 D DEVICES     : found device "STMicroelectronics Composite HID Keyboard and Touchpad" sources 0x00020004
12-09 19:53:24.244 12775 12775 D DEVICES     : found device "Logitech Wireless Receiver Mouse" sources 0x00020004
12-09 19:53:24.244 12775 12775 D DEVICES     : found device "MX Keys Keyboard" sources 0x01020315
12-09 19:53:24.244 12775 12775 D DEVICES     : requesting stylus false
12-09 19:53:24.244 12775 12775 D DEVICES     : external keyboard connected true
12-09 19:53:24.244 12775 12775 I ImeTracker  : com.termux.x11:6d27f8c2: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
12-09 19:53:24.245 12775 12775 D InputDeviceListener: changed MX Keys Keyboard
12-09 19:53:24.245 12775 12775 D DEVICES     : external keyboard connected false
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "Virtual" keyboard sources 0x00000301
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "uinput-egis" sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "gpio-keys" sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "qpnp_pon" sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "NVTCapacitiveTouchScreen" sources 0x00001103
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "double-tap" sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "kona-wcd9380-awinic-snd-card Headset Jack" sources 0x80000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "C-Media Electronics Inc. USB Audio Device" sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "STMicroelectronics Composite HID Keyboard and Touchpad Keyboard" external keyboard sources 0x00000101
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "STMicroelectronics Composite HID Keyboard and Touchpad" sources 0x00020004
12-09 19:53:24.245 12775 12775 D DEVICES     : found device "Logitech Wireless Receiver Mouse" sources 0x00020004
12-09 19:53:24.246 12775 12775 D DEVICES     : found device "MX Keys Keyboard" sources 0x01020315
12-09 19:53:24.246 12775 12775 D DEVICES     : requesting stylus false
12-09 19:53:24.246 12775 12775 D DEVICES     : external keyboard connected true
12-09 19:53:24.246 12775 12775 I ImeTracker  : com.termux.x11:e52ad3a7: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
12-09 19:53:24.388 12775 12775 D AndroidRuntime: Shutting down VM
--------- beginning of crash ---------
12-09 19:53:24.389 12775 12775 E AndroidRuntime: FATAL EXCEPTION: main
12-09 19:53:24.389 12775 12775 E AndroidRuntime: Process: com.termux.x11, PID: 12775
12-09 19:53:24.389 12775 12775 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.view.InputDevice.getName()' on a null object reference
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at com.termux.x11.input.TouchInputHandler$2.onInputDeviceChanged(TouchInputHandler.java:227)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at android.hardware.input.InputManagerGlobal$InputDeviceListenerDelegate.handleMessage(InputManagerGlobal.java:329)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:107)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at android.os.Looper.loopOnce(Looper.java:232)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:317)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:8592)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-09 19:53:24.389 12775 12775 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
12-09 19:53:27.706  9441  9456 D gles-renderer: 3 frames in 5.0 seconds = 0.6 FPS
12-09 19:53:29.536 12775 12785 I com.termux.x11: Thread[4,tid=12785,WaitingInMainSignalCatcherLoop,Thread*=0xb400007d9d0342c0,peer=0x12c401a0,"Signal Catcher"]: reacting to signal 3
12-09 19:53:29.802 12775 12785 I com.termux.x11: Wrote stack traces to tombstoned
12-09 19:53:32.706  9441  9456 D gles-renderer: 1 frames in 5.0 seconds = 0.2 FPS
12-09 19:53:35.014  9441  9456 I Adreno       : DequeueBuffer: dequeueBuffer failed
12-09 19:53:35.014  9441  9456 D gles-renderer: Xlorie: egl error on line 599: EGL not initialized or failed to initialize
12-09 19:53:35.014  9441  9456 D gles-renderer: We've got EGL_BAD_SURFACE so window is to be destroyed. Native window disconnected/abandoned, probably activity is destroyed or in background

```

### What steps will reproduce the bug?

1) Use BT / USB Keyboard
2) Start writing
3) Disconnect
4) Connect
5) It should crash or goto 2 :D

**Comment by twaik** [comment]
Did you test the latest version? Because it should be fixed by https://github.com/termux/termux-x11/commit/21213c1d7e832c63beab377ba2619bed0bac737d .

**Comment by IntinteDAO** [comment]
Yep, it looks like it fixed. Sorry and closing
