### ISSUE TITLE
[Bug]: dbus-launch: not found

### ISSUE THREAD

**Issue by HaHmada** [termux/termux-x11#767]
### Problem description

I Running Termux X11, But I Get This Error
```
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:103)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:157)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at com.termux.x11.CmdEntryPoint.lambda$spawnListeningThread$1(CmdEntryPoint.java:144)
        at com.termux.x11.CmdEntryPoint.$r8$lambda$ViPcpFnEzoJCKyl-YNiduQ0Vo1o(CmdEntryPoint.java:0)
        at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:60)
        at libcore.io.IoBridge.bind(IoBridge.java:99)
        ... 8 more
sh: 1: dbus-launch: not found
20646 exited, status=127
```

### What steps will reproduce the bug?

TwT

### What is the expected behavior?

TwT

**Comment by twaik** [comment]
1. EADDRINUSE  means you tried to launch termux-x11 twice.
2. Not found means you did not install it. Not termux-x11 related problem.

**Comment by Biswa96** [comment]
> 1. EADDRINUSE  means you tried to launch termux-x11 twice.

Should not termux-x11 prevent that like pacman uses lock file?

**Comment by twaik** [comment]
C part does this. Java part does not. I am going to fix this a bit later, it is not critical.

**Comment by twaik** [comment]
Ok, it took a bit more effort than I thought, but now it should not appear ever again.
