### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.termux.x11.starter.Starter.checkXdgRuntimeDir()

### ISSUE THREAD

**Issue by T-Dynamos** [termux/termux-x11#94]
Error file starting
```

~ $ termux-x11 :1 >/dev/null &
[5] 25276
~ $ java.lang.UnsatisfiedLinkError: No implementation found for void com.termux.x11.starter.Starter.checkXdgRuntimeDir() (tried Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir and Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir__)
        at com.termux.x11.starter.Starter.checkXdgRuntimeDir(Native Method)
        at com.termux.x11.starter.Starter.onRun(Starter.java:83)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:60)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:760)
```

I did everything fine ??

**Comment by twaik** [comment]
I am on it.
Duplicate https://github.com/termux/termux-x11/issues/56, https://github.com/termux/termux-x11/issues/70.
